const dictionary = [
    "ahole",
    "anal",
    "arsehole",
    "ass",
    "bastard",
    "bitch",
    "tits",
    "blow job",
    "blowjob",
    "camel toe",
    "chink",
    "cock",
    "creampie",
    "cum",
    "cumming",
    "cunnilingus",
    "cunt",
    "dick",
    "ejaculation",
    "fuck",
    "faggot",
    "penis",
    "pussy",
    "shit",
    "vagina",
    "wetback",
    "whore",
];

exports.filter = new RegExp(dictionary.join("|"), "gi");
